version: '3.8'
services:
  node:
    build:
      context: .
    working_dir: /app
    volumes:
      - ./src:/app
    tty: true
    ports:
      - "3000:3000"
    environment:
      JWT_SECRET: $JWT_SECRET
      DYNAMODB_ENDPOINT: $DYNAMODB_ENDPOINT
      DYNAMODB_REGION: $DYNAMODB_REGION
      DYNAMODB_ACCESS_KEY_ID: $DYNAMODB_ACCESS_KEY_ID
      DYNAMODB_SECRET_ACCESS_KEY: $DYNAMODB_SECRET_ACCESS_KEY
      LOCAL_RUNNING: $LOCAL_RUNNING
    depends_on:
      - dynamodb-local

  dynamodb-local:
    image: amazon/dynamodb-local:1.19.0
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal
