version: '3.8'
services:
  node:
    image: node:18.7-bullseye
    volumes:
      - .:/app
    tty: true
    ports:
      - "3000:3000"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASS
      TZ: 'Asia/Tokyo'
