openapi: 3.1.0
x-stoplight:
  id: r5pcu6kbmatm3
info:
  title: TodoApi
  version: '1.0'
  description: |-
    このAPIは、Todoアプリから使われることを想定したREST APIです。
    Todoデータの作成、更新、情報取得、削除などが可能ですが、各エンドポイントへのアクセスにはトークンによる認証が必要となります。
    認証に使用するユーザデータの作成、更新、情報取得や、作成したユーザへのログインについてもこのAPIから行うことができます。
  contact:
    name: iridon0920
    url: 'https://github.com/iridon0920'
    email: iridon0920@gmail.com
  summary: Todo リスト用 REST API
servers:
  - url: 'http://localhost:3000'
    description: ローカル環境で稼働時のURL
paths:
  /user:
    post:
      summary: 新規ユーザ作成
      operationId: post-user
      responses:
        '201':
          description: 作成完了
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '400':
          $ref: '#/components/responses/Bad-Request'
      description: |-
        新しいユーザを作成します。
        既に登録しているメールアドレスは使用できません。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: '#/components/schemas/userName'
                email:
                  $ref: '#/components/schemas/email'
                password:
                  $ref: '#/components/schemas/password'
              required:
                - name
                - email
                - password
        description: ''
    get:
      summary: 認証ユーザ情報取得
      operationId: get-user
      responses:
        '200':
          description: 取得完了
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '401':
          $ref: '#/components/responses/Unauthorized'
      description: トークンで認証したユーザの情報を取得します。
      security:
        - oauth2: []
      parameters:
        - $ref: '#/components/parameters/Authorization-Header'
    patch:
      summary: 認証ユーザ情報更新
      operationId: patch-user
      responses:
        '200':
          description: 更新完了
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        '400':
          $ref: '#/components/responses/Bad-Request'
        '401':
          $ref: '#/components/responses/Unauthorized'
      description: トークンで認証したユーザの情報を更新します。
      security:
        - oauth2: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  $ref: '#/components/schemas/userName'
              required:
                - name
      parameters:
        - $ref: '#/components/parameters/Authorization-Header'
    delete:
      summary: 認証ユーザ情報削除
      operationId: delete-user
      responses:
        '200':
          description: 削除完了
        '401':
          $ref: '#/components/responses/Unauthorized'
      description: トークンで認証したユーザの情報を削除します。
      security:
        - oauth2: []
      parameters:
        - $ref: '#/components/parameters/Authorization-Header'
  /todos:
    get:
      summary: Todo 検索
      responses:
        '200':
          description: 検索結果の取得完了
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/todo'
        '401':
          $ref: '#/components/responses/Unauthorized'
      operationId: get-todos
      description: サーバに保存されている全てのTodoを検索パラメータに従って取得します。
      security:
        - oauth2: []
      parameters:
        - $ref: '#/components/parameters/Authorization-Header'
        - schema:
            type: string
          in: query
          name: title
          description: Todoのタイトル。前方一致で検索。
        - schema:
            type: string
            format: uuid
          in: query
          name: userId
          description: ユーザID。完全一致で検索。
    post:
      summary: 新規Todo作成
      operationId: post-todos
      responses:
        '200':
          description: 作成完了
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/todo'
        '400':
          $ref: '#/components/responses/Unauthorized'
        '401':
          $ref: '#/components/responses/Unauthorized'
      description: 認証ユーザに紐づく新しいTodoを作成します。
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  $ref: '#/components/schemas/todoTitle'
                content:
                  $ref: '#/components/schemas/todoContent'
  '/todos/{todoId}':
    parameters:
      - schema:
          type: string
        name: todoId
        in: path
        required: true
        description: TodoのID
    get:
      summary: Todo情報取得
      responses:
        '200':
          description: Todo情報の取得
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/todo'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/Not-Found'
      operationId: get-todos-todoId
      security:
        - oauth2: []
      parameters:
        - $ref: '#/components/parameters/Authorization-Header'
      description: Idで指定したTodo情報を取得します。他ユーザの作成したTodoの情報も取得可能です。
    delete:
      summary: Todo情報削除
      operationId: delete-todos-todoId
      responses:
        '200':
          description: 削除完了
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/Not-Found'
      description: Idで指定したTodoを削除します。他ユーザが作成したTodoは削除できません。
    patch:
      summary: Todo情報更新
      operationId: patch-todos-todoId
      responses:
        '200':
          description: '更新完了  '
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/todo'
        '400':
          $ref: '#/components/responses/Bad-Request'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/Not-Found'
      description: Idで指定したTodoを更新します。他ユーザが作成したTodoは更新できません。
      security:
        - oauth2: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  $ref: '#/components/schemas/todoTitle'
                content:
                  $ref: '#/components/schemas/todoContent'
  /auth/login:
    parameters: []
    post:
      summary: ユーザログイン
      operationId: post-auth-login
      responses:
        '200':
          description: ログイン完了
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
        '401':
          description: 認証失敗
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusCode:
                    type: string
                    example: '401'
                  message:
                    type: string
                    example: ユーザ認証に失敗しました。
      description: 指定したユーザIDでのログインを行います。ログインが成功した場合、各リクエストで認証に使用するためのトークンが返ってきます。
      security: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  $ref: '#/components/schemas/id'
                password:
                  $ref: '#/components/schemas/password'
        description: ''
components:
  schemas:
    user:
      title: user
      x-stoplight:
        id: 2kf56o0mkzed5
      type: object
      properties:
        id:
          $ref: '#/components/schemas/id'
        name:
          $ref: '#/components/schemas/userName'
        email:
          $ref: '#/components/schemas/email'
    userName:
      type: string
      title: ユーザ名
      x-stoplight:
        id: 3a6e0hdg8m7om
      minLength: 1
      maxLength: 30
    email:
      type: string
      title: email
      x-stoplight:
        id: 80g94yz9qeeph
      description: |-
        一般的なメールアドレスの形式に準拠している必要があります。
        ローカル部分は最大64文字まで、ドメイン部分は最大253文字までです。
      maxLength: 256
      format: email
    password:
      type: string
      title: password
      x-stoplight:
        id: vi2teciia5kgq
      minLength: 8
      format: password
    todo:
      title: todo
      x-stoplight:
        id: rb7p0rkqmedyk
      type: object
      properties:
        id:
          $ref: '#/components/schemas/id'
        title:
          $ref: '#/components/schemas/todoTitle'
        content:
          $ref: '#/components/schemas/todoContent'
    todoTitle:
      type: string
      title: todoTitle
      x-stoplight:
        id: eluyajbaa3yx4
      minLength: 1
      maxLength: 500
    todoContent:
      type: string
      title: todoContent
      x-stoplight:
        id: 0sk40vj0g89hi
      minLength: 1
      maxLength: 15000
    id:
      type: string
      title: id
      x-stoplight:
        id: e86h20qy8gxq7
      format: uuid
      description: サーバにて生成したUUID
  securitySchemes:
    oauth2:
      type: oauth2
      flows:
        password:
          tokenUrl: 'http://localhost:3000/auth/login'
          refreshUrl: ''
          scopes: {}
      description: このエンドポイントでは、ログインによって取得したトークンをリクエストヘッダに付ける必要があります。
  parameters:
    Authorization-Header:
      name: Authorization Header
      in: header
      required: true
      schema:
        type: string
        example: Bearer <token>
      description: Bearer認証を行うためのトークンを記述する
  requestBodies: {}
  responses:
    Unauthorized:
      description: トークンによる認証の失敗
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: number
                example: 401
              message:
                type: string
                example: Unauthorized
      headers: {}
    Not-Found:
      description: 指定したIDに該当するデータが存在しない。
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: string
                example: '404'
              message:
                type: string
                example: 指定したデータが見つかりません。
    Bad-Request:
      description: リクエストパラメータに何らかの問題あり。
      content:
        application/json:
          schema:
            type: object
            properties:
              statusCode:
                type: string
                example: '400'
              message:
                type: string
                example: （例）ユーザ名の長さは30文字以内にしてください。
  examples: {}
